# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
